version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - backend/.env
    environment:
      - HOST=0.0.0.0
      - PORT=8000
    volumes:
      - ./backend/data:/app/data
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    environment:
      - REACT_APP_API_BASE=http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend