version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - OPENAI_API_KEY
      - OPENAI_BASE_URL=https://openrouter.ai/api/v1
      - OPENAI_MODEL=deepseek/deepseek-chat-v3-0324:free
    volumes:
      - ./backend/data:/app/data
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    environment:
      - REACT_APP_API_BASE=http://localhost:8000/api
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_started